= Projektbeschreibung ROARS: Entwicklungshandbuch
:author: Thomas Peetz
:email: <thomas.peetz@cimt-ag.de>
:doctype: report
:sectnums:
:sectnumlevels: 4
:toc:
:toclevels: 4
:table-caption!:
:counter: table-number: 0

[title="Dokumenthistorie", id="Table-{counter:table-number}", options="header"]
|===
| Version | Datum      | Autor        | Änderungsgrund / Bemerkungen
| 0.1.0   | 30.10.2025 | Thomas Peetz | Ersterstellung
|===

== Allgemeines

=== Zweck des Dokumentes

Das Entwicklungshandbuch beschreibt die Werkzeuge und die Vorgehensweise bei der Entwicklung
im Projekt kontor-spring und der Erstellung der Dokumentation.

=== Verwendete Tools

== Erstellung der Dokumentation

Die Dokumentation des Projektes wird mit ((Asciidoctor))<<asciidoctor>> geschrieben.
Die Dokumente erhalten ihre Namen nach dem jeweiligen Hauptdokument.

=== Quellcode Verwaltung

Die Asciidoctor-Dateien haben die Endung `.adoc`.

=== Buildsystem

Zur Erstellung der PDF-Dateien aus den Asciidoctor-Dateien wird das Buildsystem ((Gradle))<<gradle>> verwendet.
Die Dateien für die Dokumente liegen im Verzeichnis `src/docs/asciidoc`.

Der Gradle Build wird über die Datei `build.gradle` definiert.


== Einführung

=== Zweck
