= Projektbeschreibung PURR Ablösung
:author: Thomas Peetz
:email: <thomas.peetz@cimt-ag.de>
:doctype: article
:sectnums:
:sectnumlevels: 4
:toc:
:toclevels: 4
:table-caption!:
:counter: table-number: 0

[title="Dokumenthistorie", id="Table-{counter:table-number}", options="header"]
|===
| Version | Datum      | Autor        | Änderungsgrund / Bemerkungen
| Draft   | 08.12.2025 | Thomas Peetz | Ersterstellung
|===

== Allgemeines

=== Zweck des Dokumentes

Zur Ablösung der Platz- und Raumreservierung <<purr>>(((PURR))) soll ein neues Projekt aufgesetzt werden.
Dieses Dokument dient als Grundlage für das Kickoff-Meeting, das im Januar 2026 stattfinden soll.
Es werden die Gründe für eine Neuentwicklung, die anfängliche Projektorganisation und die ersten Anforderungen beschrieben.

== Projektbeschreibung

Ein Platzreservierungs-Tool soll die Planung für die Leitung und die einzelnen Mitarbeiter erleichtern.
Neben der statistischen Auswertung der Auslastung der Arbeitsplätze und der Koordination der Mitarbeiter untereinander, sowie der Nutzung der
Meetingräume ist auch die Einhaltung der Büroanwesenheit eine zentrale Aufgabe der Lösung.

=== Ausgangslage

In der cimt objects Berlin wurde die Software (((Deskbird))) eingesetzt und durch die in Hamburg erstellte Lösung <<purr>>(((PURR))) ersetzt.

Das Projekt ((PURR)) wurde als Ausbildungsprojekt in der cimt consulting Hamburg gestartet und wird dort von Werkstudenten etnwickelt.
Die Anforderungen wurden hauptsächlich durch den Hamburger Standort bestimmt.
Durch die erweiterte Nutzung durch den Berliner Standort wurden weitere Anforderungen gestellt, die durch Berliner Kollegen bearbeitet wurden.
Die neuen Anforderungen wurden nur zum Teil umgesetzt, da die Architektur und das Datenmodell eine Weiterentwicklung erschwert haben.

Die Verwendung von ((PHP)) soll durch andere Frameworks ersetzt werden.

==== Rechtliche Vorgaben und Rahmenbedingungen

Durch die Speicherung der Reservierungen der Mitarbeiter der cimt consulting und der cimt objects sind die Datenschutzrichtlinien strikt einzuhalten.

=== Rahmenbedingungen

==== Vorhandene Regelungen

Für den Standort Hamburg ist die Bestätigung der Reservierung am Vortag der Reservierung eine der Anforderungen, die im neuen Projekt ebenfalls enthalten sein muss.

=== Projektziele

Dieses Projekt soll ((PURR)) ablösen und dabei neue Anforderungen integrieren.
Der ursprüngliche Gedanke das Projekt zur Ausbildung zu nutzen, soll auch in diesem Projekt umgesetzt werden.
In Vorbereitung auf den Projektstart werden nachfolgend Anforderungen und Abnahmekriterien beschrieben, die für <<purr>>(((PURR))) erfasst wurden.

==== Anforderungen

- Alternative Arbeitsorte (mobiles Arbeiten, Geschäftsreise, Kundenbesuch, abwesend)
- Responsive UI (mobile Ansicht)
- Wochenübersicht
- Schnellbuchung
- Mehrere Plätze buchen
- Bilder anzeigen
- Abwesenheiten aus ZEP übertragen
- Wochen- oder Monatsbuchung
- Wochentag benennen
- Wochenenden ausblenden
- Zeitfokussierte Buchungsansicht  
- Bevorzugte Arbeitsplätze definieren
- Antwort <5 s auch beim Start
- Standortfilter auch bei “Reservieren für andere”
- Präzisere Wortwahl in der UI
- Beschriftung von Räumen und Plätzen im Tischplan
- Obligatorisches Check-in für Standort abschaffen   
- Meetingraum-Reservierungen anzeigen
- Eindeutige, teilbare, Bookmarkable Urls
- Anzeige der Anwesenheitsziele
- Report zu Anwesenheitszielen

==== Abnahmekriterien

- Browsercache beinflusst nicht die Anzeige

=== Projektabgrenzung

Die Unzufriedenheit mit <<purr>> führte zu Konkurrenzprojekten <<ritch>> und <<roars>>.
Diese Projekte wurden unabhängig und auf eigene Initiative gestartet und sind nicht aktiv beziehungsweise eingestellt.

=== Voraussichtliche Kosten

=== Projektrisiken

==== Produktivität

==== Finanzielle Risiken

==== Akzeptanz

Die Akzeptanz wird durch die Benutzer in Pre-Prod-Deployments gemessen.

== Projektorganisation

=== Projekt-Aufbauorganisation

==== Teilprojekte

Die aktuelle Architektur sieht getrennte Frontend- und Backend-Services vor.
Die Trennung von Frontend und Backend entkoppelt die Entwicklung und bedingt eine Design-By-Contract Methodik.

=== Rollendefinition

Das Projekt soll mit Hilfe von agilen Methoden umgesetzt werden.

==== Projektauftraggeber

Das Projekt wird von der cimt objects Berlin initiiert und betrieben.
Eine Ausweitung der Nutzung durch andere Standorte und andere cimt Gesellschaften wird bei Akzeptanz nach Inbetriebnahme berücksichtigt.

==== Projektausschuss

==== Qualitätssicherung

Die Qualitätssicherung ist eine zentrale Funktion in der Entwicklung und wird zum Teil in der Entwicklung von Beginn an implementiert.
Die weiteren Aufgaben der Qualitätssicherung in Bezug auf Sicherheit wird durch die Product Owner und den Development Lead koordiniert.

==== Auftraggeber

Der Auftraggeber stellt Anforderungen und nimmt das Projekt ab.

==== Product Owner

Der Product Owner verwaltet das Backlog und priorisiert die Anforderungen.

==== Development Lead

Der Development Lead koordiniert die Entwicklungsaufgaben und das Team der Entwickler.

==== Projektteam

Das Projektteam besteht aus festgelegten Mitglieder, wie in der <<Table-2, Tabelle 2>> beschrieben und Kollegen, die bestimmte Aaufgaben übernehmen.

==== Liste der Stakeholder

Die Stakeholder werden durch die Leitung von cimt objects Berlin vertreten.

=== Projektablauforganisation

==== Projekt-Phasen

Das Projekt wird iterativ in Sprints nach der Scrum Methode durchgeführt.
Das Team legt in Abstimmung mit den <<Product Owner>> die Ziele des jeweiligen Sprints fest.

In Vorbereitung auf das Kickoff-Meeting werden nachfolgend erforderliche Anforderungen für die ersten Sprints genannt:

- Aufsetzen der Entwicklungsumgebung für verschiedene Bereiche (Test, Produktion)
- Implementierung der Anmeldung über den Windows Login
- Erstellung des Datenbankmodells nach den bisher gesammelten Anforderungen der PURR-Anwender aus Berlin
- Entscheidung über die Synchronisation der Daten aus PURR in dieses Projekt

===== Erstellung der Projektdokumentation

Die Projektdokumentation wird in Confluence geschrieben, um allen Beteiligten die Inoformationen zugänglich zu machen.
Die Einrichtung eines Ticketsystems (Jira, GitHub, o.ä.) wird im Kickoff-Meeting entschieden.

== Verschiedenes

=== Erreichbarkeiten

[title="Erreichbarkeiten", id="Table-{counter:table-number}", options="header"]
|===
| Rolle                | Name               | Email
| <<Product Owner>>    | John Wieland Höche | john-wieland.hoeche@cimt-ag.de
| <<Product Owner>>    | Geraldine Bauer    | geraldine.bauer@cimt-ag.de
| <<Development Lead>> | Thomas Peetz       | thomas.peetz@cimt-ag.de
| <<Auftraggeber>>     | Oliver Fromm       | oliver.fromm@cimt-ag.de
| <<Auftraggeber>>     | Frank Füllbier     | frank.fuellbier@cimt-ag.de
|===


[appendix]
== Architektur Vorschläge

Für die Neuentwicklung stehen verschiedene Frameworks und Programmiersprachen zur Auswahl.

=== Server-Side Script Language

<<purr>> ist in PHP entwickelt und kommt ohne weitere Frameworks aus.


=== Trennung von Frontend und Backend

Zur Entkoppelung von Frontend und Backend stehen unterschiedliche Frameworks zur Auswahl.
Eine Trennung vereinfacht die Entwicklung und bedingt das Design-By-Contract Prinzip.

==== Backend

Das Backend beinhaltet den Zugang zur Datenbank und administrativer Aufgaben.
Für externen Zugang (Frontend und andere) wird ein REST-Interface bereitgestellt.

===== Python

Ein REST-Interface in Python kann mit Hilfe verschiedener Frameworks implementiert werden.
Flask und Django sind mögliche Kandidaten.

===== Java

Für Java existieren verschiedene Frameworks, wie z.B. Javalin, Quarkus oder Springboot.
Diese Frameworks unterscheiden sich in der Nutzung von Resources, Dependency-Injection und IDE Unterstützung.

==== Frontend

Als Programmiersprachen sind Javascript und Typescript die häufigsten Vertreter.

===== Angular

Angular ist mit dem gesamten Ökosystem die gängigste Wahl für Unternehmensanwendungen.

===== Vue.js

Vue.js ist eine leichtgewichtige Alternative zu Angular und eines der Merkmale ist die Definition von Layout, Script und Style in einer .vue-Datei.

===== React

React ist ein weiteres Framework, das in der Webentwicklung Verwendung findet.

[appendix, bibliography]
== Referenzen

[appendix, glossary]
== Glossar

[horizontal, glossary]
[[purr]]PURR:: Platz- und Raum-Reservierung
[[ritch]]RITCH:: Reservation Interface & Tracking Control Hub
[[roars]]ROARS:: Reservation Objects Attendance Retrieval System

[appendix, index]
== Index

[appendix]
== Verzeichnisse

=== Abbildungsverzeichnis

=== Tabellenverzeichnis

- <<Table-1, Tabelle 1>> <<Table-1>>
- <<Table-2, Tabelle 2>> <<Table-2>>
